CREATE DATABASE accommodation ENCODING 'UTF8';
CREATE DATABASE address ENCODING 'UTF8';
CREATE DATABASE auth ENCODING 'UTF8';
CREATE DATABASE booking ENCODING 'UTF8';
CREATE DATABASE payment ENCODING 'UTF8';

