eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8082

spring:
  application:
    name: accommodation-service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/accommodation
    username: postgres
    password: Q12345w6

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  redis:
#    host: redis
#    port: 6379
#    timeout: 60000
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 5
#        min-idle: 2
#        time-between-eviction-runs: 60000
#
#  cache:
#    type: redis

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    export:
      prometheus:
        enabled: true

  endpoint:
    prometheus:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
