eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8081

spring:
  application:
    name: auth-service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/auth
    username: postgres
    password: Q12345w6
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  redis:
 #   host: localhost
 #   port: 6379
jwt:
  secret: "my-very-very-secret-key-should-be-long"
  expiration: 86400000

service:
  security:
    trusted:
      booking-service: booking123
      accommodation-service: accommodation123
      payment-service: payment123
      notification-service: notification123


management:
  endpoints:
    web:
      exposure:
        include: health,info
    endpoint:
      health:
        show-details: always

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

