eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8084

spring:
  application:
    name: booking-service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/booking
    username: postgres
    password: Q12345w6

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false

    consumer:
      group-id: ${spring.application.name}-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.samilyak.bookingservice.dto.event

    listener:
      ack-mode: RECORD
      missing-topics-fatal: false

application:
  kafka:
    topics:
      booking-cancellation-requested: booking.cancellation.requested.v1
      payment-canceled: payment.canceled.v1
      dates-unlocked: accommodation.dates.unlocked.v1

  redis:
    host: localhost
    port: 6379
    timeout: 60000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 2
        time-between-eviction-runs: 60000

  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    export:
      prometheus:
        enabled: true

  endpoint:
    prometheus:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
##      defaultZone: http://eureka-server:8761/eureka/
#  instance:
#    preferIpAddress: true
#
#server:
#  port: 8084
#
#spring:
#  application:
#    name: booking-service
#
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    enabled: true
#
#service:
#  security:
#    username: booking-service
#    password: booking123
#
#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://postgres:5432/booking
#    username: postgres
#    password: Q12345w6
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  redis:
#    host: redis
#    port: 6379
#    timeout: 60000
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 5
#        min-idle: 2
#        time-between-eviction-runs: 60000
#
#  cache:
#    type: redis
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#    endpoint:
#      health:
#        show-details: always

#  tracing:
#    sampling:
#      probability: 1.0
#
#  zipkin:
#    tracing:
#      enabled: true
